### ISSUE TITLE
依赖重复报警告（dependencies和devDependencies）

### ISSUE THREAD

**Issue by GuoJikun** [purple-force/docsite#79]
系统环境：
docsite   v1.3.9
node  v12.18.3
npm  6.14.6
系统  win10 专业版 20170.rc

package 截图 如下：
![image](https://pic.imgdb.cn/item/5f50bf46160a154a6733314e.png)

**Comment by GuoJikun** [comment]
这个项目没人维护了吗？这种小问题都没人管？

**Comment by chengshiwen** [comment]
@GuoJikun I forked this repo, enhanced and resolved it, please refer to https://github.com/chengshiwen/docsite-ext, and [Apache DolphinScheduler Official Website](https://dolphinscheduler.apache.org/) used it
