### ISSUE TITLE
初始化完成后，启动报错

### ISSUE THREAD

**Issue by GuoJikun** [purple-force/docsite#80]
运行环境：
docsite v1.3.9
node v12.18.3
npm 6.14.6
系统 win10 专业版 20170.rc

错误截图：
![image](https://pic.downk.cc/item/5f50bf46160a154a67333166.png)

**Comment by purple-force** [comment]
截图显示不了，你把node版本切换到10再试试看

**Comment by guojikun** [comment]
> 截图显示不了，你把node版本切换到10再试试看

图片已经显示了

**Comment by purple-force** [comment]
node版本换成10

**Comment by 48654586love** [comment]
> node版本换成10

了解了，这是还不支持node > 10吗？

**Comment by purple-force** [comment]
初始化出来的前端工程，里面的 一些工程依赖比较老旧

**Comment by heson10** [comment]
建议优化一下，支持最新的npm 12

**Comment by jimmyleeking** [comment]
这是一个Dead库了吗，怎么连最基本的Node版本都不支持了呢？

**Comment by wf123537200** [comment]
这种依赖很多的情况是不是应该吧package-lock一起传上来，不然跑不起来

**Comment by 521qq** [comment]
> 这种依赖很多的情况是不是应该吧package-lock一起传上来，不然跑不起来

说的对，不然npm audit fix都会报错:  Errors were found in your package-lock.json

**Comment by GuoJikun** [comment]
> > 这种依赖很多的情况是不是应该吧package-lock一起传上来，不然跑不起来
> 
> 说的对，不然npm audit fix都会报错: Errors were found in your package-lock.json

需要先`npm i`之后再执行`npm audit fix`

**Comment by Hanson-Hao-Wu** [comment]
这个项目是停止维护了吗？

**Comment by chengshiwen** [comment]
I forked this repo, enhanced and resolved it, please refer to https://github.com/chengshiwen/docsite-ext, and [Apache DolphinScheduler Official Website](https://dolphinscheduler.apache.org/) used it
